### ISSUE TITLE
The balloon isn't doing anything

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#376] opened 2016-10-11 01:08 UTC
It just sits there on the street in front of the ship, which is not great.

@xhoogland, could you please take a look?

**Comment by xhoogland** [comment] 2016-10-23 14:40
It weirdly somehow seems like this isn't happening anymore. George afaik created a property on the arrow-place and since that time the balloon was stuck sometimes.

Since I have moved that property this bug looks to be disappeared... :o

**Comment by HolsjeLVP** [comment] 2016-10-23 16:08
http://puu.sh/rSTin/727b7476ee.jpg

It stayed like this for a while. When a player used the balloon and got on the arrow it went back up.

Seems like it doesn't always register a player leaving the arrow?

**Comment by xhoogland** [comment] 2016-12-11 01:37
According to @DeerHunterLVP it does not happen anymore, so closing this. :) Feel free to re-open if you see this or can reproduce this!

**Closed as completed by xhoogland** 2016-12-11 01:37 UTC
Labels: bug
