### ISSUE TITLE
Races Do not stop you before the CD ends

### ISSUE THREAD

**Issue by HaloLVP** [LVPlayground/playground#456] opened 2017-02-09 04:35 UTC
When you start any race by example /race 1, you can start running before the 3, 2, 1 GO!

**Comment by xhoogland** [comment] 2017-02-09 17:44
@RussellLVP, if you have time - could you please take a look at this? If I replace https://github.com/LVPlayground/playground/blob/master/javascript/features/races/race_minigame.js#L94 directly with `pawnInvoke('TogglePlayerControllable', 'ii', player.id, 0);` (like https://github.com/LVPlayground/playground/blob/master/javascript/entities/player.js#L173) it does NOT work either. Could this be some bug in pawnInvoke?

Thank you!

**Comment by ghost** [comment] 2017-02-11 18:46
This is a duplicate of https://github.com/LVPlayground/playground/issues/428 - unsure which we want to keep open given the extra info in this.

**Comment by RussellLVP** [comment] 2020-04-28 20:51
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!

Halo, specifically for the bugs you've filed: thank you so incredibly much! They're all great and valid bugs, but with the amount of development time we have available nowadays (near 0!) many are sadly not worth fixing.

**Closed as completed by RussellLVP** 2020-04-28 20:51 UTC
