### ISSUE TITLE
High Packet Loss high ID

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#5] opened 2015-10-13 19:16 UTC
http://trac.sa-mp.nl/lvp/ticket/1571

eF.Holsje:

> If it's busy, about 20/30ish people only, the players with higher IDs will get HUGE Packet Loss (Increasing over time), around 25% (Where like 2% is already very bad).
> 
> Currently testing it, but it seems to be true that EVERY high ID gets high Packet Loss over time (About 10~20minutes to get to your full 20%+)

eF.Holsje:

> Now some time later (With half the players online) it seems like my PacketLoss? is fixed, but still gives the 20% value. However the 20% value appears to be fake as I don't notice any warping, and others don't notice me warping anymore.

striker:

> It's possible that players with higher ID's gets somehow messed up. We had this before where players receive godmode or doesn't spawn properly. Though I don't really remember why it happened.
> As I noticed some of you messing with /v create to add lord knows how many vehicles. It's good to keep in mind why we had less vehicles and not too crowded around, especially where people fight. The combination of rockets, grenade in an area/range where there's too many vehicles, a player FPS could drop drastically. I've experienced that myself.
> 
> I believe Russell himself said that also. There's people that still got crappy computers and that could increase the chances of lagging and crashing.
> The command /stats used to show how many properties and vehicles and other important information. I don't know if that's being displayed right now.
> We had around ~1100 vehicles with a limit of ~1200. 
> It's always good to know exactly when and report right away if something is wrong. This could help the developers looking into the problem. By now the server has been pushed with 2-3 updates, which could make it harder to find out what exactly is causing the lag etc. If nothing can be found then I would start by removing those vehicles back and leave it the way it was.
> 
> Edit: It can be also a hacker spawning multiple vehicles. Sometimes you may not even get close to where they are and you start to lag, FPS drop to 5 and your game crash. That's why we have the command to respawn vehicles. But I doubt it's that right now, but it's worth letting others know as its similar to having lots of vehicles crowded around.

striker:

> I forgot to say this also. If things like this happens again, make a topic in Crew also because this is something serious and those that could possibly help may not be active on trac but on forum instead.

Granny:

> The vehicles have been cleaned up (myself and Gibbs got a little too carried away, sorry). I've opened a topic in the crew forum.

Xanland:

> > Optimized some for-loops with MAX_PLAYERS to PlayerManager??->highestPlayerId()
> > Replaced some IsPlayerConnected/?-NPC with Player-> variant for faster access
> 
> Related to r5123, although it is a tiny change and I doubt it fixes it though!

**Comment by RussellLVP** [comment] 2015-10-19 10:25
We're very bad at scaling at the moment. I implemented a bunch of optimizations, but it's nowhere near enough. We need profiles when there are more than 10 players in-game, but since finalizing a profile requires us to restart the server it's not easy to get them.

**Comment by jadegraaf** [comment] 2015-10-19 10:35
@RussellLVP Regarding those profiles, what do they track at this moment? Would problems with the vehicle streamer be shown for example?

**Comment by ghost** [comment] 2015-10-24 16:35
Few seconds on the server and I get packetloss like this. 
![Alt Text](http://i57.tinypic.com/2hi47f9.jpgl)
Had ID 28, I've checked everybody from lower ID to higher ones and ID 36 had a stable 25.5 packetloss.
Ignore my FPS, it was all normal after a few seconds. Everybody had packetloss but as the ID increases so does the packetloss however that isn't the case every time.

**Comment by debuggest3** [comment] 2015-12-24 16:59
Luce had a suggestion which I think is worth looking into. We have a beautiful live map on our website, which uses data that is updated every second by the gamemode.

Are we sure that updating this data by the gamemode isn't too taxing?

**Comment by BeanerLVP** [comment] 2015-12-24 18:47
MrBondt, are you referring to https://sa-mp.nl/map/ ?
We've had this map for over a year or two, and I'm sure nobody faced such packet loss issues when it was live back then. 
Of course, I'm not aware if any technical changes were made, so I can't be sure now.

**Comment by xhoogland** [comment] 2015-12-25 15:27
Since my lack of communication about this topic to others:
I talked about this with Peter and what probably could have caused this. My conclusion, and kinda Peter's too, that the method we use to show this percentage is f*cked. We use the https://wiki.sa-mp.com/wiki/NetStats_PacketLossPercent in our code and that is also what you see in the right hand corner.
Meanwhile if you look up your SA-MP-statistics by pressing some SA-MP default F-key, you also see a packetloss percentage statistic. That one is far more accurate then the one we are showing. To be honest at the end is that I still don't know what and how it's causing this.

If the loss we show is accurate, it is actually - what I heard - impossible to play or even to connect. 

About the map: Isn't the map getting the coordinates from the MySQL-database we use?

**Comment by jadegraaf** [comment] 2015-12-25 15:37
@Xanland so there is a significant difference between the packet loss in the text draw and in the sa-mp statistics? Is there any 'real' (sa-mp) packet loss at all?

**Comment by debuggest3** [comment] 2015-12-25 16:01
Whether the number is right or not doesn't matter. The issues people experience are very real:
- When ramping, ramps appearing too late and the vehicle getting stuck inside said ramp
- Commands taking a long time (3-5 seconds) to execute

There are no doubt even more complaints. I think we should stop staring at this abstract "packet loss" percentage and focus instead on fixing actual problems players have.

People are complaining about lag in the main chat, but what did they experience? If we can find that out, we have more information to work with and a better chance of fixing this "packet loss" issue.

**Comment by xhoogland** [comment] 2015-12-25 16:14
Yes, the difference between those two can be huge. In the most cases the real loss is 0.0%.

![sa-mp-059](https://cloud.githubusercontent.com/assets/15852015/12003693/e6eb273a-ab2a-11e5-9be1-90a51af77d70.png)
![sa-mp-060](https://cloud.githubusercontent.com/assets/15852015/12003694/e6ef10e8-ab2a-11e5-8f60-7ef676c817a8.png)
![sa-mp-063](https://cloud.githubusercontent.com/assets/15852015/12003828/caed873a-ab2f-11e5-85a0-21446786d525.png)

**Comment by xhoogland** [comment] 2015-12-31 03:12
Centered the other two statistics in commit https://github.com/LVPlayground/playground/commit/0f4325d84ae462b0c84f0f93676221dc215b0437.

My suggestion would be to close this issue and look for the real issue's, like @dgrp is saying?

**Comment by ghost** [comment] 2016-01-04 12:43
I've come to accept, based on what numerous people have said, that the "Loss" reported ingame isn't accurate, and based on SA:MP's wiki saying it's not accurate/reliable, I'm not worried about that anymore. 

Holding F5 shows 0.0% packetloss.

However, this problem is more than cosmetic. I've been ingame for the last few minutes, with just 20 players in total. Commands are slow to execute, ramps aren't spawning (sometimes at all) or they spawn too late and my car gets stuck in them. I'm going to throw some thoughts out there:
- Do we have too many saved vehicles on the map? Is it worthwhile removing all vehicles from the map, just for testing purposes?
- Do we have too many properties? There's currently 337
- Could this be caused by one (or more) of the NPCs? E.g. TrainDriverLS, PilotLV, etc.
- Are there any fragmented database tables, and, are all the tables healthy (not crashed/in need of repair)?
- Could one of the IRC bots (Monique, Nuwani, Saber, etc) be requesting too much data, too quickly? 
- LVP Radio: perhaps that could be responsible?

Think of Linux Operating Systems...CentOS 6 64-bit, and CentOS 6 64-bit Minimal. Is there a way we could start a "minimal" version of LVP for a couple hours?

**Comment by ghost** [comment] 2016-01-10 11:57
Updating this with some notes from Darkfire:

[10/01/2016 - 11:19:13] @Darkfire I played samp a bit the past days, mostly on FFS / LW though
[10/01/2016 - 11:19:20] @Darkfire I notice LVP is way more laggy then those servers
[10/01/2016 - 11:20:38] @Darkfire my FPS was alot higher on both LW and FFS
[10/01/2016 - 11:20:43] @Darkfire and they had more players aswell ;s
[10/01/2016 - 11:22:12] <&Granny> In what way do you feel the lag? As in, do people's vehicles warp all over the place, chatlag, or ..?
[10/01/2016 - 11:22:48] @Darkfire game is slower
[10/01/2016 - 11:23:07] @Darkfire like when I fight people, I feel both they and I lagg alot

I've quizzed various players about this subject, and the general consensus is that this never used to be a problem and that the gamemode felt much more sharp and responsive.

I don't know if any of this helps, but I figured, the more feedback and thoughts, the better the chance we have of reaching a resolution.

**Comment by ghost** [comment] 2016-01-17 14:29
I discussed this with cake today:

cake: vehicleStreamIn is called a lot
cake: that could cause lag
cake: you remember the vehicles misplacing bug?
cake: I then implemented a fix that, when a vehicle streams in for a player, repositions the vehicle
cake: I can assume that could induce some lag, even fps like lag
cake: and also, the packetloss seems to remain constant
cake: even when you're standing still
cake: so thats kinda weird..
cake: its in Entities\Vehicles\VehicleEvents.pwn
cake: public onVehicleStreamIn(playerId) {}

**Comment by xhoogland** [comment] 2016-01-17 19:06
I changed that method where cake is talking about so it does less
repositioning. In the ideal situation we fix that whole positioning issue
at the right place.

Do keep in mind that the only RIGHT packetloss is in the F5-statistics!

But still I kinda doubt that that is a huge part of our issue, since there
are issues afaik already with a non-LVP gamemode.

**Comment by mblokker** [comment] 2016-01-17 19:18
The whole issue is the fact that one experiences an awful lot of lag, with or without the (correct) packetloss indicators.

Player/vehicle streaming is happening multiple times per second, which might have an influence, just crossing possibilities of the list.

This is the first time I hear someone saying it is not related to LVP, most people state the opposite.
Could it be 0.3.7? We could do a downgrade to 0.3z for funz and testing.

**Comment by xhoogland** [comment] 2016-01-17 22:26
[23:20:14] Xanland: [16:33:30] MrBondt - about that packetloss issue: How much problems can the IRC bots actually cause? I always am saying they don't, but I think you can say a bit more about it. I would say only when they are running on the gameserver and even then it would be low.
[23:20:14] MrBondt: [17:38:22] in normal operation, none. It could be a problem if the bot starts sending a lot of rcon commands which triggers heavy operations within the gamemode. Outputting the echo has no direct impact on the gamemode, as the gamemode writes events to a socket which is polled by the bot. I have no idea what the impact of sockets is in Pawn, but it should be fairly low as well.
[23:20:14] MrBondt: [17:39:51] however, a test with an empty gamemode has proven to be laggy as well, so something is up with sa-mp itself anyway
[23:20:14] Xanland: [18:02:45] Hhmm, would suck if it was sa-mp itself to be honest. I'm wondering how other server-owners are dealing with such issues, although they mostly are placed in the US with US players. Giving more people good ping.
[23:20:14] Peter: [18:06:17] nah
[23:20:14] Peter: [18:06:20] they're all russian these days
[23:20:14] Peter: [18:06:36] I think there's settings for the network/gameplay update timers
[23:20:14] Peter: [18:06:40] could try changing these

I don't know exactly what kind of tests were done, but this is what @dgrp and @beverloo said on my question about if the IRC-bots could cause anything.

**Comment by ghost** [comment] 2016-02-04 21:01
II was having some extremely noticeable lag, and I heard complaints from another player at the same time too. I decided to start a 60 second /trace

Results: http://pastebin.com/raw/du8GPJUw

No idea if that will help, but I figured I'd share it nevertheless.

**Comment by ghost** [comment] 2016-03-09 17:50
It seems that there's not much of an improvement, if at all. 

I'd like to propose that we disable LVP Radio for a week for experimentation purposes. The lag seems to be more extreme the more players we have in-game, and perhaps the radio streaming is choking us somewhere. I know that Russell has said we're not I/O, Bandwidth & CPU bound as everything checked out there, but it's worth giving it a shot. 

It's not like we're going to see players leave because of no radio, after all. 

I still hear players saying say play elsewhere because of lag, such as one of our admins who faces issues on LVP, but no other servers.

Furthermore, I've heard numerous players state that the radio causes them to lag or crash, which I can confirm. It's for this reason I always /audiomsg and /radio as soon as I join. There's a relevant thread, here: https://forum.sa-mp.nl/showthread.php?tid=32728

Admin Slide tells me this:

[Slide] btw before i crashed today, radio link got spammed 
[Slide]  stopped and started
[Slide]  about 8 times or so
[Slide]  mp3 file or w/e its called

**Comment by xhoogland** [comment] 2016-03-09 21:35
Sorry for berks/berkley/Mark (radio-owner?), but I guess it is worth a try to be honest. Unless we have people who are thinking otherwise?

Of course I keep the vehicleStreamIn disabled!

**Comment by ghost** [comment] 2016-03-11 21:37
An admin tells me that a server he plays on doubled the player slots which caused noticeable lag (whilst seeing no increase in players). We peak at 60 players at the very best of times, perhaps we should decrease our slots from 127 to 75. I see no harm in trying.

Furthermore, I've read that OnPlayerUpdate can contribute to poor performance, which we seem to use (albeit just once).

Also timers - are there any we can remove/replace/optimize without major work?

**Comment by ghost** [comment] 2016-03-17 07:28
Closing this as the streamer plugin was updated, which looked likely to be the cause. Will re-open if I hear or see any future complaints.

**Closed as completed by ghost** 2016-03-17 07:28 UTC
Labels: priority, bug
