### ISSUE TITLE
Crashed on race 3 initialization

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#167] opened 2016-05-15 12:40 UTC
SA:MP crash output below. I have no mods installed.

SA-MP 0.3.7
Exception At Address: 0x0074DA25
Base: 0x04220000

Registers:
EAX: 0xC1000000 EBX: 0x00000010 ECX: 0x00000B7D EDX: 0x00000000
ESI: 0xC1000000 EDI: 0x0D60B7E0 EBP: 0x1BBF67A0 ESP: 0x0177F754
EFLAGS: 0x00210283

Stack:
+0000: 0x00000007   0x0074E171   0xC1000000   0x1BBF6780
+0010: 0x1B6FC9F8   0x0E760504   0x00000000   0x0074CD3E
+0020: 0x1BBF67A0   0x0E7605DC   0x0074A366   0x1BBF6780
+0030: 0x00002EE0   0x00B45494   0xFFFFFFFF   0x00B45494
+0040: 0x004C4EA9   0x1B874AB8   0x00000258   0x004089DD
+0050: 0x00000000   0x0177F7DC   0x00000258   0x0EF65728
+0060: 0x042D2483   0x00000258   0x00000511   0x0EF65728
+0070: 0x0EE4EEE0   0x0EF65728   0x00000258   0x0177F968
+0080: 0x042F2718   0x00000000   0x0EE52158   0x042D25F8
+0090: 0x0EE52158   0x0423AFD9   0x00000001   0x0EE91BD8
+00A0: 0x00000258   0x0444C44A   0xFF000511   0x00000001
+00B0: 0x0177F97C   0x0177FA5C   0xFF000511   0x0EF65728
+00C0: 0x3FFFFFFF   0x00000200   0x00000200   0x000001F8
+00D0: 0x0177F940   0x00000000   0x00200206   0x0EE91DD0
+00E0: 0x0177F97C   0x0177FA5C   0x0177F850   0x00000001
+00F0: 0x4512AC28   0x0177F854   0x0177F850   0x00000000
+0100: 0x00000018   0x00000018   0x00000010   0x0177F97C
+0110: 0x00000000   0x00000000   0x00000000   0x00000000
+0120: 0x00000000   0x00000000   0x00000000   0x00000000
+0130: 0x00000000   0x00000000   0x00000000   0x00000000
+0140: 0x00000000   0x00000000   0x00000000   0x00000000
+0150: 0x00000000   0x00000000   0x00000000   0x00000000
+0160: 0x00000000   0x00000000   0x00000000   0x00000000
+0170: 0x00000000   0x00000000   0x00000000   0x00000000
+0180: 0x00000000   0x00000000   0x00000000   0x00000000
+0190: 0x00000000   0x00000000   0x00000000   0x00000000
+01A0: 0x01972F94   0x00000000   0x008E2270   0x0080875D
+01B0: 0x1B6F37E8   0x000000A4   0x1B6F37E8   0x04257440
+01C0: 0x0EE91AD8   0x0177F940   0x0177FA5C   0x0177F934
+01D0: 0x00000001   0x0000001D   0x0177FAB8   0xDF128700
+01E0: 0xDF128700   0x04257440   0x04257466   0x0177F98C
+01F0: 0x0177FA5C   0x0177FAA4   0x0177FAA4   0x0423C071
+0200: 0x0177FAA4   0x00000000   0x0EE91BD8   0x0177FA5C
+0210: 0x00000001   0x0177FAB8   0x044B900B   0x00000000
+0220: 0x04257440   0x0177FAA0   0x04250511   0x0EF6C4C2
+0230: 0x0EF6C4C0   0x00000000   0x00000030   0x00000030
+0240: 0x0000002C   0x0EF37820   0x01CF6D00   0x000E00B8
+0250: 0x0EFB67A0   0x00000001   0x00000000   0x1C1AC468
+0260: 0x00000000   0x00000000   0x1C1AC468   0x01CF6DC0
+0270: 0x7CC61C3F   0x0177FA04   0x54FF036B   0x000E07D0

SCM Op: 0x248, lDbg: 0 LastRendObj: 3460

Game Version: US 1.0

State Information: Ped Context: 0
P0 (0,0) P1 (0,0) P2 (0,0) P3 (0,0) 
P4 (0,0) P5 (0,0) P6 (0,0) P7 (0,0) 
P8 (0,0) P9 (0,0) P10 (0,0) P11 (0,0) 
P12 (0,0) P14 (0,0) P15 (0,0) 
P16 (32,0) P19 (17,0) 
P20 (17,1541) P21 (0,0) P22 (32,0) P23 (0,0) 
P24 (32,0) P26 (0,0) P30 (0,0) P37 (0,0) P38 (0,0)

**Comment by mblokker** [comment] 2016-05-27 09:17
As far as crashes go; I cannot distill any information from these crash reports. Since I can't reproduce this, and haven't seen others reporting this, I will close this out for now.

**Closed as completed by mblokker** 2016-05-27 09:17 UTC
Labels: bug
