### ISSUE TITLE
Saved skin not reloading after /stopwatch

### ISSUE THREAD

**Issue by harryrf3** [LVPlayground/playground#144] opened 2016-04-09 19:10 UTC
After /watch'ing a player then using /stopwatch I've noticed that my skin does not reload to what is saved in /my skin save.

This has happened on both an undercover account and an alias of my main account. Never tried it on my main account, but will update after testing.

**Update**: I went in-game under my main name, Harry, and this is what I found.

I chose a skin at the main selection screen and pressed spawn. I wanted to change my skin again so I assigned a skin (159) using the command /p ID skin SKIN_ID. Afterwards I used /my skin save. After using /watch then /stopwatch, the skin I first selected at the selection screen reloaded and not the one I saved.

After some more testing I kept getting the same results, even after using /my skin remove then redoing what I did above, I had the same result. What I found worked was removing my skin, using F4 then /kill. After selecting a skin again before respawning, I used /my skin save. Then after using /watch /stopwatch, the skin I saved, and just selected at the selection screen was reloaded without any further input.

So, the skin picked at the selection screen continues to reload regardless of it being saved or not. Using /p ID skin SKINID then /my skin save does not override the skin selected at the selection screen. The one selected at the selection screen seems to save as a default.

**Comment by RussellLVP** [comment] 2016-05-07 18:32
I landed a potential fix in the following commit: https://github.com/LVPlayground/playground/commit/db8a9007f785773cad2800271c65bd1589741c61

Please test it out at your earliest convenience and let me know whether it helped. Thank you for the detailed report :)

**Comment by ghost** [comment] 2016-05-15 11:37
@harryrf - have you managed to test this out? It's live on the main server :)

(personally I've not been able to re-produce this issue)

**Comment by mblokker** [comment] 2016-05-24 08:23
Let's close this out since GeorgeLVP hasn't been able to reproduce it.

**Closed as completed by mblokker** 2016-05-24 08:23 UTC
Labels: bug
