### ISSUE TITLE
Many black colours on the live player map

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#19] opened 2015-10-13 20:46 UTC
(From http://trac.sa-mp.nl/lvp/ticket/1439)

Many players have black icons on https://sa-mp.nl/map/. They're set to zero in the database, so this likely is a gamemode issue.

**Comment by mblokker** [comment] 2016-02-18 13:29
The issue right now seems to be the that the colors are mainly white.

E.g. some players have decimal colors like -2103588950 in the database (table 'online'), which translates to FFFFFFFF829DC7AA, which states actually two colors (FFFFFFFF) and (829DC7AA). The map then shows the first color (white).

The problem is that InvalidColorId in ColorManager.pwn is stated as -1, which actually translates to FFFFFFFFFFFFFFFF. Then, when the player color is saved, only the last 8 chars are replaced, which results in the problem described earlier.

This can be fixed by using InvalidColorId: 0xFFFFFFFF (or 4294967295, but yay for hex).

**Closed as completed** 2016-02-18 13:33 UTC
Labels: bug
