### ISSUE TITLE
Race System :: /leave isn't working 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#177] opened 2016-05-20 20:29 UTC
This evening I was unable to /leave a race. I had confirmation to suggest this was successful, but all the race checkpoints and features remained.

Screenshot: http://i.imgur.com/UoY7TOh.jpg

**Comment by mblokker** [comment] 2016-05-27 09:13
I cannot reproduce this, can you?

**Comment by ghost** [comment] 2016-05-27 09:27
I just tried this once more on the main server (15 players ingame) and the results were exactly the same as those I originally reported. Used /race 1, but it seems to happen in any of them.

**Comment by mblokker** [comment] 2016-05-27 09:29
Thanks for checking! Weird staging server/main server differences. We should check this again if LVP 28.2 is pushed to main.

**Comment by mblokker** [comment] 2016-05-27 18:42
Seems to be working, closing out.

**Closed as completed by mblokker** 2016-05-27 18:42 UTC
Labels: bug
