### ISSUE TITLE
Export Car for Merchant spawning multiple vehicles at the same time. 

### ISSUE THREAD

**Issue by TFarish** [LVPlayground/playground#64] opened 2015-12-24 08:55 UTC
There's been a couple of times where I've noticed that when you go to the merchant car that is wanted that there is around 50 other vehicles around the car itself. 

The 2 places I've noticed it so far are on mt chilliad and just outside SF near to the airport. I'm unsure if it's caused solely in these locations or if it's a general issue..

**Comment by ghost** [comment] 2015-12-24 11:03
hmm.... you want to say That you can't unterstand where Is the merchant Car ! Around Many other 50 cars ? ??..............

**Comment by TFarish** [comment] 2015-12-24 16:28
No... I said exactly what I mean. Where the car spawns for the merchant, another 50 spawn with it.

**Comment by ghost** [comment] 2015-12-24 16:29
Ohh ... I have not noticed yet

**Comment by jadegraaf** [comment] 2015-12-24 17:05
@TFarish are the symptoms equal to https://github.com/LVPlayground/playground/issues/18?

Like: http://i.imgur.com/eK18oBy.jpg a lot of sports cars randomly appearing close to a merchant location, not the merchant vehicle appearing 50 times like @HopperLVP deducted.

Thank you for the report.

**Comment by TFarish** [comment] 2015-12-24 17:06
Yes oost. They may be related.

**Comment by jadegraaf** [comment] 2015-12-24 17:17
Thanks for your response, I will close this issue and append your information the other report.

Duplicate of #18

**Closed as completed by jadegraaf** 2015-12-24 17:17 UTC
